# Generated by Django 2.2.4 on 2021-05-22 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210522_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='applied_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 8, 42, 15, 243653, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 8, 42, 15, 243653, tzinfo=utc)),
        ),
    ]
