# Generated by Django 2.2.4 on 2021-05-22 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210522_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='applied_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 9, 11, 28, 82047, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 9, 11, 28, 72047, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='degree_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='depart_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='skill',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
